### ISSUE TITLE
Python Notebooks for plots for the paper templates

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/psat-ligo-resources#1]
Make python notebooks with the lightcurve plots for the paper. 

**Figure 1** : Skymap of the GW contours and the footprints of our coverage (@thespacedoctor) 

**Figure 2** :  Discovery image : a quad of target, reference and difference along with a colour image of the host location. (Michael) 

**Figure 3** : Simple plot of all the data we have, y-axis should be apparent mag, x-axis in days since GW.  No reddening corrections or any other corrections applied, just the data (Thomas/Michael/Shubham)

**Figure 4** : Comparison plot of the lightcurves with 2017gfo (depending on what filter we have). Absolute mag vs time since GW (ThomasMichael/Shubham) 

**Figure 5** : Lightcurve data and model fits (Matt and Thomas). Either photometric bands or bolometric LC versus time.

**Comment by smarttgit** [comment]
Other figures we should get ready in case the data we have data to suit 

**Figure 6** : SED of the photometry (or any spectrum we have) versus the spectrum of 2017gfo 

**Figure 7**:  SED of the photometry (or any spectrum we have) versus the model spectra for different Ye calculated in Gillanders et al. 2022.

**Comment by AstronoMoore** [comment]
Google Collab notebooks for figures 3-5 are completed. Do we have a location on  the PSAT wiki to add these links?

**Comment by AstronoMoore** [comment]
Figures 3-5 added to the Overleaf template with links to notebooks
