### ISSUE TITLE
Make sure GCN Template generator (plain text and latex) is available on Pan-STARRS and ATLAS web pages

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/psat-ligo-resources#21]
The Pan-STARRS / ATLAS pages used to have a GCN generator. Make sure this code is still working or modify to get it working.

**Comment by genghisken** [comment]
The code for generating text and LaTeX templates exists in Pan-STARRS, but is not currently working correctly. The text template exists in ATLAS, but it's not wired into the URL configuration yet.

**Comment by smarttgit** [comment]
Refers to tables of objects from database

**Comment by genghisken** [comment]
Add list of events to paste into the AstroNote. These will be cut/pasted into the AstroNote for use by the TNS tool that automatically adds references to the TNS entries. The table can then be removed before submission.

Additionally or alternatively, the table could be added with URLS so we can some summary info around the object (which contour it's in, etc).
